theme: minima
title: SeonWoo Lee title
author: SeonWoo Lee
email: zzz664@naver.com
description: Practice github

# social links
twitter_username: none # DO NOT include the @ character, or else the build will fail!
github_username:  SeonWoo Lee # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
