---
title: "SeonWoo Lee site"
date: 2020-04-04
---
theme: minima
title: SeonWoo Lee site
author: SeonWoo Lee
email: zzz664@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Practice github

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
